name: Build and Run Test

on:
  push:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: self-hosted
    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # 3. Construir y ejecutar con Docker Compose
    - name: Run Docker Compose
      run: |
        docker-compose up --build --abort-on-container-exit
        docker-compose down --rmi all --volumes --remove-orphans