name: Self-hosted Runner Test

on:
  push:
    branches:
      - main

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Set Execution Policy
        shell: powershell
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force
          Write-Host "Execution policy set to Bypass"
      - name: Check Runner
        shell: powershell
        run: echo "This is running on my self-hosted runner!"
